### ISSUE TITLE
Issues with the dafni upload dataset-version command

### ISSUE THREAD

**Issue by rich970ea** [dafnifacility/cli#135]
**Problem Description**
I am getting the following error when using the template command:
`dafni upload dataset-version VERSION_ID file.zip -m "Some message"`

`Error: No such option: -m`

So, I try instead using --version-message in place of -m, since this looks to be an alias for this based on the `dafni upload dataset-version --help` output

`dafni upload dataset-version VERSION_ID file.zip --version-message "Some message"`

and get the following

`Confirm dataset upload? [y/N]: y
Validating metadata
Dataset metadata validation failed. The following errors were returned:
Error: The schema for uploading metadata onto DAFNI can be found at https://github.com/dafnifacility/metadata-schema.
Error: Error: Additional properties are not allowed ('dataset_type' was unexpected). Occurred at Path: []`

**Environment**
Python 3.7 (note, my colleague who is using Python >3.9 also has this issue though)

certifi            2023.11.17
charset-normalizer 3.3.2
click              8.1.7
colorama           0.4.6
dafni-cli          1.0.5
idna               3.6
importlib-metadata 7.0.0
pip                23.3.1
python-dateutil    2.8.2
requests           2.31.0
setuptools         40.8.0
six                1.16.0
tabulate           0.9.0
tqdm               4.66.1
typing_extensions  4.7.1
urllib3            2.1.0
zipp               3.17.0

**Comment by sarahbyrnie** [comment]
Thank you for reporting this. This bug has now been fixed and we have released an updated version v1.0.6 of the CLI
