### ISSUE TITLE
Refactor new util methods and better init method into Model

### ISSUE THREAD

**Issue by iroper-tessella** [dafnifacility/cli#38]
The dataset methods use some helpful general methods found in the `utils.py` file which can be used in the `Model`, `ModelMetadata` and `VersionHistory` classes.

Additionally, the way in which the `DatasetMetadata` class is initialised is better than the current way that these model-based classes are initialised. This should be adopted into these classes also.

**Comment by sarahbyrnie** [comment]
This is an outdated issue
